version: "3.9"

services:
  ets2convoys:
    build: .
    volumes:
      - ./gamedata:/gamedata:rw
    network_mode: host
    restart: unless-stopped
    ports:
      - "27015:27015"
      - "27016:27016"
      - "27015:27015/udp"
      - "27016:27016/udp"
